---
kind: pipeline
name: go

steps:
  - name: testing
    image: golang:1.15.5
    pull: true
    commands:
      - go get github.com/go-bindata/go-bindata/...
      - go get github.com/elazarl/go-bindata-assetfs/...
      - go generate ./cmd/webtail/...
      - go test -coverprofile=coverage.out -covermode=atomic ./...
      - go vet ./...
      - curl -s https://codecov.io/bash | bash
    environment:
      CODECOV_TOKEN:
        from_secret: my-codecov-token

---
kind: pipeline
name: docker

steps:
  - name: build
    image: docker/compose
    commands:
      - apk add --no-cache curl git make jq
      - make docker-build
      - docker images
