kind: pipeline
name: ci

steps:
- name: fetch tags
  image: alpine/git
  commands:
  - git fetch --tags
  - git describe --tags --always > .version

- name: test app
  image: golang:1.15.5
  commands:
  - go get github.com/go-bindata/go-bindata/...
  - go get github.com/elazarl/go-bindata-assetfs/...
  - go generate ./cmd/webtail/...
  - go test -coverprofile=coverage.out -covermode=atomic ./...
  - go vet ./...
  - curl -s https://codecov.io/bash | bash
  environment:
    CODECOV_TOKEN:
      from_secret: my-codecov-token

- name: test docker build
  image: plugins/docker
  settings:
    repo: testbuild
    dry_run: true
    build_args:
      - GOLANG_VERSION=1.15.5-alpine3.12
  when:
    event:
      exclude:
      - tag

- name: publish docker
  image: plugins/docker
  settings:
    repo: ghcr.io/lekovr/${DRONE_REPO_NAME}
    registry: https://ghcr.io
    username: ${DRONE_REPO_OWNER}
    password:
      from_secret: my-docker-token
    auto_tag: true
    tags: latest
    custom_labels: org.opencontainers.image.source=${DRONE_REPO_LINK}
    label_schema: description="Tail [log]files via web"
    build_args:
      - GOLANG_VERSION=1.15.5-alpine3.12
  when:
    event:
    - tag
