version: '2.1'

services:

  app:
    image: ${DC_IMAGE}
    command:
      /server --listen :8081 --log_level debug --root /data
    ports:
      - "${SERVER_PORT}:8081"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ${LOG_DIR}:/data
    build:
      context: .
      args:
        - golang_version
