version: '2.1'

services:

  app:
    image: ${DOCKER_IMAGE}
    ports:
      - "${SERVER_PORT}:8080"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ${LOG_DIR}:/log
    build:
      context: .
      args:
        - GOLANG_VERSION
        - GOPROXY
