#!/bin/bash

# $IMAGE_NAME var is injected into the build so the tag is correct.

echo "Build hook running"
docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
             --build-arg VCS_REF=`git rev-parse --short HEAD` \
             --build-arg APP_VERSION=`git describe --tags --always` \
             --build-arg GOLANG_VERSION=1.15.5-alpine3.12 \
             -t $IMAGE_NAME .
